const $=(s,r=document)=>r.querySelector(s)
const send=(message)=>new Promise((resolve,reject)=>chrome.runtime.sendMessage(message,(result)=>{const error=chrome.runtime.lastError;if(error)return reject(new Error(error.message));if(!result?.ok)return reject(new Error(result?.error||'extension did not respond'));resolve(result.data)}))
const esc=(value)=>String(value??'').replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const symbols={USD:'$',EUR:'€',GBP:'£',INR:'₹',JPY:'¥'}
const minor=(value,currency)=>Math.round(Number(value||0)*(currency==='JPY'?1:100))
const money=(value,currency)=>(symbols[currency]||currency+' ')+(value/(currency==='JPY'?1:100)).toFixed(currency==='JPY'?0:2)
let config,account,detection,selected=new Map()

async function boot(){
  try{config=await send({type:'config'})}catch{config={engine:'https://engine-production-e6fa.up.railway.app',app:'https://sutra-gmp.vercel.app'}}
  if(!config.sessionToken)return renderConnect()
  try{account=await send({type:'account'});$('#account').innerHTML=`<b>${esc(account.user.name)}</b><div class="sub">@${esc(account.user.handle)}</div>`}
  catch(error){return renderConnect(error.message)}
  try{detection=await send({type:'detect'});renderReview()}catch(error){$('#main').innerHTML=`<div class="card"><b>This page could not be read.</b><div class="error">${esc(error.message)}</div><button class="cta secondary" id="retry">Try again</button></div>`;$('#retry').onclick=boot}
}

function renderConnect(message=''){$('#account').innerHTML='';$('#main').innerHTML=`<div class="card connect"><div class="mark" style="margin:auto"></div><h2>One account.<br>Every surface.</h2><p class="meta">Connect this extension to the same friends, circles, plans and receipts you use in sutra.</p><button class="cta" id="open">Open account settings</button><input class="token" id="token" type="password" placeholder="Paste extension token"><button class="cta secondary" id="save">Connect extension</button>${message?`<div class="error">${esc(message)}</div>`:''}<div class="note">The token is scoped to your account and stored only on this device—not inside the page.</div></div>`;$('#open').onclick=()=>chrome.tabs.create({url:config.app+'/app/settings'});$('#save').onclick=async()=>{const token=$('#token').value.trim();if(!token)return;await send({type:'save-config',patch:{sessionToken:token}});location.reload()}}

function renderReview(){
  const currency=(detection.currency||'USD').toUpperCase(),unit=detection.items?.[0]?.unit_amount||detection.total_minor||0,qty=detection.items?.[0]?.qty||1
  const circles=account.circles||[],friends=account.friends||[];selected=new Map([[account.user.id,account.user]])
  $('#main').innerHTML=`<div class="card product">${detection.image?`<img src="${esc(detection.image)}">`:'<div class="mark"></div>'}<div><div class="kicker">${esc(detection.merchant?.name||'Detected page')}</div><div class="title">${esc(detection.title||'Untitled item')}</div><div class="meta">${money(unit*qty,currency)} · ${esc(detection.strategy?.[0]||'page')}</div><span class="confidence">${Math.round((detection.confidence||0)*100)}% match</span></div></div>
  ${circles.length?`<div class="section"><div class="label"><span>Start with a circle</span><span>${circles.length}</span></div>${circles.map(c=>`<button class="circle" data-circle="${esc(c.id)}"><b>${esc(c.emoji)} ${esc(c.name)}</b><div class="sub">${c.members.length} people</div></button>`).join('')}</div>`:''}
  <div class="section"><div class="label"><span>People</span><span id="count">1 selected</span></div><div class="people"><button class="person on" data-id="${esc(account.user.id)}">You</button>${friends.map(f=>`<button class="person" data-id="${esc(f.id)}">${esc(f.name)}</button>`).join('')}</div></div>
  <div class="section"><div class="label"><span>Amount and quantity</span></div><div class="grid"><input id="price" inputmode="decimal" value="${(unit/(currency==='JPY'?1:100)).toFixed(currency==='JPY'?0:2)}"><input id="qty" type="number" min="1" max="99" value="${qty}"></div></div>
  <div class="section"><select id="policy"><option value="all_of">Everyone approves</option><option value="quorum">Majority approves</option><option value="deadline">Whoever is in by deadline</option></select></div>
  <div class="sum"><div><span>Total</span><div id="total"></div></div><div style="text-align:right"><span>Per person</span><br><b id="each"></b></div></div><button class="cta" id="create">Create group</button><div id="error"></div><div class="links"><button class="link" id="settings">Account settings</button><button class="link" id="disconnect">Disconnect</button></div><div class="note">Importing a page does not authorize a merchant checkout. sutra coordinates consent and payment only on supported rails.</div>`
  const update=()=>{const total=minor($('#price').value,currency)*Math.max(1,Number($('#qty').value)||1);$('#total').textContent=money(total,currency);$('#each').textContent=money(Math.floor(total/Math.max(1,selected.size)),currency);$('#count').textContent=`${selected.size} selected`}
  document.querySelectorAll('[data-id]').forEach(button=>button.onclick=()=>{const id=button.dataset.id;if(id===account.user.id)return;const person=friends.find(f=>f.id===id);selected.has(id)?selected.delete(id):selected.set(id,person);button.classList.toggle('on',selected.has(id));update()})
  document.querySelectorAll('[data-circle]').forEach(button=>button.onclick=()=>{const circle=circles.find(c=>c.id===button.dataset.circle);selected=new Map(circle.members.map(m=>[m.id,m]));document.querySelectorAll('[data-circle]').forEach(x=>x.classList.toggle('on',x===button));document.querySelectorAll('[data-id]').forEach(x=>x.classList.toggle('on',selected.has(x.dataset.id)));update()})
  $('#price').oninput=update;$('#qty').oninput=update;$('#settings').onclick=()=>chrome.tabs.create({url:config.app+'/app/settings'});$('#disconnect').onclick=async()=>{await send({type:'save-config',patch:{sessionToken:''}});location.reload()};$('#create').onclick=()=>create(currency);update()
}

async function create(currency){const button=$('#create'),people=[...selected.values()],deadline=config.deadlineMinutes||60,kind=$('#policy').value,quorum=Math.max(1,Math.ceil(people.length*.6)),policy=kind==='quorum'?{type:'quorum',m:quorum}:kind==='deadline'?{type:'deadline',at:new Date(Date.now()+deadline*60000).toISOString(),primary:{type:'all_of'},fallback:{type:'quorum',m:quorum}}:{type:'all_of'};button.disabled=true;button.textContent='Creating your group…';try{const result=await send({type:'create',group:{title:(detection.title||'Group purchase').slice(0,140),merchant:{id:'extension',name:(detection.merchant?.name||'Merchant').slice(0,80),url:detection.merchant?.url||location.href,country_code_iso2:'US'},cart:{items:[{sku:'extension-item',name:(detection.title||'Item').slice(0,100),unit_amount:minor($('#price').value,currency),qty:Math.max(1,Number($('#qty').value)||1),claimants:['mi_all']}],fees:[],currency},members:people.map(p=>({name:p.name,role:'payer',user_id:p.id})),policy,deadline_minutes:deadline}});const board=new URL(result.board_url,config.app).href;$('#main').innerHTML=`<div class="card connect"><div style="font-size:38px">✓</div><h2>Group is live.</h2><p class="meta">${result.members.length} people can now review their exact share.</p><button class="cta" id="board">Open group board</button><div class="note">Merchant checkout remains a separate handoff unless that merchant supports a sutra payment adapter.</div></div>`;$('#board').onclick=()=>chrome.tabs.create({url:board})}catch(error){button.disabled=false;button.textContent='Create group';$('#error').innerHTML=`<div class="error">${esc(error.message)}</div>`}}
boot()
