/* sutra widget — "request payment from everyone" on any page.
 *
 * Merchant embed (the original contract, still honoured):
 *
 *   <script src="https://ENGINE/widget.js"
 *     data-gmp-title="Ratatat — 4 tickets"
 *     data-gmp-merchant="Velvet Ticket Co."
 *     data-gmp-item="GA ticket" data-gmp-price="45.00" data-gmp-qty="4"
 *     data-gmp-members="Soham,Arsh,Dev,Maya"
 *     data-gmp-token="dev-token"></script>
 *
 * Or, now, nothing at all:
 *
 *   <script src="https://ENGINE/widget.js"></script>
 *
 * With no attributes it reads the page — JSON-LD, microdata, OpenGraph, the
 * live Shopify cart, or failing all of that the order total in the DOM — and
 * shows you what it found before it does anything. data-gmp-* attributes
 * always override detection.
 *
 * It runs on other people's pages, so: one shadow root (no CSS escapes, none
 * gets in), one global (`window.__sutra`, for idempotency and for the
 * bookmarklet/extension to call `open()`), and every entry point wrapped so a
 * failure here can never become a failure in the host page.
 */
;(function () {
  'use strict'

  // The inlined detector assigns to this local `module`, not to `window`.
  var module = { exports: {} }

  /* >>> BEGIN INLINED widget/detect.js — generated by widget/build-bookmarklet.mjs, do not edit */
/* sutra · detect.js — read a cart/product/order out of ANY page.
 *
 *   SutraDetect.detectCart(document, location)  ->  Promise<Detection>
 *   SutraDetect.detectCartSync(document, location) -> Detection   (no network)
 *
 * Six strategies, tried in order, each contributing fields to one merged
 * result that carries provenance for every field it filled:
 *
 *   json-ld · microdata · og/meta · shopify · dom-total · selection
 *
 * Design rules, because this runs on a stranger's page:
 *   - zero dependencies, no globals beyond `SutraDetect`, never throws.
 *   - every number is INTEGER MINOR UNITS. No floats past the parser.
 *   - confidence is earned. Structured data is high, DOM scraping is low,
 *     and we would rather return `total_minor: null` than a number that
 *     isn't money.
 *
 * UMD: CommonJS (so node:test can require it), AMD, or window global.
 */
;(function (root, factory) {
  'use strict'
  /* eslint-disable no-undef */
  if (typeof module === 'object' && module && module.exports) module.exports = factory()
  else if (typeof define === 'function' && define.amd) define([], factory)
  else (root || this).SutraDetect = factory()
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  'use strict'

  var VERSION = '1.0.0'

  // ---------------------------------------------------------------------
  // Money
  // ---------------------------------------------------------------------

  // Currencies whose minor unit is not 1/100.
  var EXPONENT = {
    JPY: 0, KRW: 0, VND: 0, CLP: 0, ISK: 0, PYG: 0, RWF: 0, UGX: 0, VUV: 0,
    XAF: 0, XOF: 0, XPF: 0, KMF: 0, DJF: 0, GNF: 0, BIF: 0,
    BHD: 3, KWD: 3, OMR: 3, JOD: 3, TND: 3, IQD: 3, LYD: 3,
  }

  // Longest-first so 'HK$' beats '$' and 'R$' beats 'R'.
  var SYMBOLS = [
    ['HK$', 'HKD'], ['NZ$', 'NZD'], ['A$', 'AUD'], ['C$', 'CAD'], ['S$', 'SGD'],
    ['R$', 'BRL'], ['CHF', 'CHF'], ['kr.', 'DKK'], ['zł', 'PLN'], ['Kč', 'CZK'],
    ['Rs.', 'INR'], ['Rs', 'INR'], ['₹', 'INR'], ['€', 'EUR'], ['£', 'GBP'],
    ['¥', 'JPY'], ['₩', 'KRW'], ['₺', 'TRY'], ['₪', 'ILS'], ['฿', 'THB'],
    ['₫', 'VND'], ['₱', 'PHP'], ['₦', 'NGN'], ['₴', 'UAH'], ['د.إ', 'AED'],
    ['RM', 'MYR'], ['US$', 'USD'], ['$', 'USD'],
  ]

  var ISO_CODES =
    'USD|EUR|GBP|INR|CAD|AUD|JPY|CHF|SEK|NOK|DKK|PLN|CZK|HUF|RON|BGN|TRY|RUB|UAH|' +
    'CNY|HKD|TWD|SGD|MYR|THB|IDR|PHP|VND|KRW|NZD|ZAR|NGN|KES|EGP|MAD|AED|SAR|QAR|' +
    'KWD|BHD|OMR|JOD|ILS|MXN|BRL|ARS|CLP|COP|PEN|PKR|BDT|LKR|NPR|ISK'
  var ISO_RE = new RegExp('\\b(' + ISO_CODES + ')\\b')

  // TLD -> currency. Deliberately a *weak last resort*; flagged in warnings.
  var TLD_CURRENCY = {
    in: 'INR', uk: 'GBP', de: 'EUR', fr: 'EUR', es: 'EUR', it: 'EUR', nl: 'EUR',
    ie: 'EUR', pt: 'EUR', at: 'EUR', be: 'EUR', fi: 'EUR', gr: 'EUR', eu: 'EUR',
    ca: 'CAD', au: 'AUD', nz: 'NZD', jp: 'JPY', kr: 'KRW', cn: 'CNY', hk: 'HKD',
    sg: 'SGD', my: 'MYR', th: 'THB', id: 'IDR', ph: 'PHP', vn: 'VND', br: 'BRL',
    mx: 'MXN', ar: 'ARS', cl: 'CLP', co: 'COP', za: 'ZAR', ng: 'NGN', ke: 'KES',
    ae: 'AED', sa: 'SAR', ch: 'CHF', se: 'SEK', no: 'NOK', dk: 'DKK', pl: 'PLN',
    cz: 'CZK', tr: 'TRY', ru: 'RUB', ua: 'UAH', pk: 'PKR', bd: 'BDT', lk: 'LKR',
  }
  var LANG_CURRENCY = {
    'en-in': 'INR', 'hi-in': 'INR', 'en-gb': 'GBP', 'en-au': 'AUD', 'en-nz': 'NZD',
    'en-ca': 'CAD', 'fr-ca': 'CAD', 'ja-jp': 'JPY', 'ja': 'JPY', 'ko-kr': 'KRW',
    'zh-cn': 'CNY', 'zh-hk': 'HKD', 'zh-tw': 'TWD', 'de-de': 'EUR', 'de-at': 'EUR',
    'fr-fr': 'EUR', 'es-es': 'EUR', 'it-it': 'EUR', 'nl-nl': 'EUR', 'pt-pt': 'EUR',
    'pt-br': 'BRL', 'es-mx': 'MXN', 'ru-ru': 'RUB', 'tr-tr': 'TRY', 'pl-pl': 'PLN',
    'sv-se': 'SEK', 'nb-no': 'NOK', 'da-dk': 'DKK', 'th-th': 'THB', 'id-id': 'IDR',
    'vi-vn': 'VND', 'en-sg': 'SGD', 'en-za': 'ZAR', 'ar-ae': 'AED',
  }

  function minorUnits(currency) {
    var e = EXPONENT[String(currency || '').toUpperCase()]
    return Math.pow(10, e === undefined ? 2 : e)
  }

  function formatMinor(amountMinor, currency) {
    var c = String(currency || 'USD').toUpperCase()
    var e = EXPONENT[c] === undefined ? 2 : EXPONENT[c]
    return (amountMinor / Math.pow(10, e)).toFixed(e)
  }

  function currencyFromString(s) {
    var iso = ISO_RE.exec(String(s))
    if (iso) return iso[1]
    for (var i = 0; i < SYMBOLS.length; i++) {
      if (String(s).indexOf(SYMBOLS[i][0]) !== -1) return SYMBOLS[i][1]
    }
    return null
  }

  /**
   * Turn a digit-group string into a Number, deciding which separator is the
   * decimal mark. Handles US (1,234.56), European (1.234,56), Indian lakh
   * grouping (1,23,456), space grouping (1 234,56) and bare integers.
   */
  function parseGrouped(numeric) {
    numeric = numeric.replace(/[   \s'’]/g, '')
    if (!/\d/.test(numeric)) return null
    var neg = /^-/.test(numeric)
    numeric = numeric.replace(/-/g, '')

    var lastDot = numeric.lastIndexOf('.')
    var lastComma = numeric.lastIndexOf(',')
    var out
    if (lastDot === -1 && lastComma === -1) {
      out = numeric
    } else {
      var decIdx = Math.max(lastDot, lastComma)
      var decimals = numeric.length - decIdx - 1
      var bothKinds = lastDot !== -1 && lastComma !== -1
      // 1–2 digits after the final separator => it's the decimal mark.
      // Exactly 3 digits => a thousands mark (1,234 / 1.234 / 1,23,456),
      // unless it's the *only* separator and the other kind appears earlier.
      if (decimals >= 1 && decimals <= 2) {
        out = numeric.slice(0, decIdx).replace(/[.,]/g, '') + '.' + numeric.slice(decIdx + 1)
      } else if (decimals === 3 || bothKinds) {
        out = numeric.replace(/[.,]/g, '')
      } else {
        // 4+ digits after a separator is not a grouping and not a sane
        // currency decimal — refuse rather than invent a number.
        return null
      }
    }
    var v = Number(out)
    if (!isFinite(v)) return null
    return neg ? -v : v
  }

  /**
   * parseMoney('$1,234.56')        -> { amount_minor: 123456, currency: 'USD' }
   * parseMoney('₹1,23,456','INR')  -> { amount_minor: 12345600, currency: 'INR' }
   * parseMoney('1.234,56 €')       -> { amount_minor: 123456, currency: 'EUR' }
   * parseMoney(45)                 -> { amount_minor: 4500, currency: fallback }
   *
   * opts.structured: the value came from a machine-readable field (JSON-LD,
   * microdata, meta), where a bare `1.234` means one-point-two-three-four and
   * not one thousand. Grouping heuristics only kick in if it isn't a clean
   * decimal literal.
   */
  function parseMoney(raw, fallbackCurrency, opts) {
    opts = opts || {}
    if (raw === null || raw === undefined || raw === '') return null
    if (typeof raw === 'number') {
      if (!isFinite(raw)) return null
      return toMinor(raw, fallbackCurrency || 'USD')
    }
    var s = String(raw).trim()
    if (!s) return null
    if (/^(free|gratis|n\/?a|tbd|price on request)$/i.test(s)) return null

    var currency = currencyFromString(s) || fallbackCurrency || null

    var value
    if (opts.structured && /^-?\d+(\.\d+)?$/.test(s)) {
      value = Number(s)
    } else {
      var numeric = s.replace(/[^\d.,\-    ]/g, '')
      value = parseGrouped(numeric)
      if (value === null && opts.structured) {
        var plain = /-?\d+(?:\.\d+)?/.exec(s)
        value = plain ? Number(plain[0]) : null
      }
    }
    if (value === null || value === undefined || !isFinite(value)) return null
    return toMinor(value, currency || 'USD', currency === null)
  }

  function toMinor(value, currency, currencyGuessed) {
    var c = String(currency).toUpperCase()
    return {
      amount_minor: Math.round(value * minorUnits(c)),
      currency: c,
      currency_guessed: !!currencyGuessed,
    }
  }

  // A money-shaped run of text: symbol-then-number, or number-then-code.
  // A currency marker is mandatory — a bare number is never money here.
  var SYM_CLASS = '\\$|€|£|¥|₹|₩|₺|₪|฿|₫|₱|₦|₴|R\\$|A\\$|C\\$|S\\$|HK\\$|NZ\\$|US\\$|Rs\\.?|RM|zł|Kč|د\\.إ'
  var NUM = '\\d[\\d.,\\u00a0\\u202f\\u2009 ]{0,18}\\d|\\d'
  var MONEY_RE = new RegExp(
    '(?:(?:' + SYM_CLASS + '|' + ISO_CODES + ')\\s{0,2}(?:' + NUM + ')' +
    '|(?:' + NUM + ')\\s{0,2}(?:' + SYM_CLASS + '|' + ISO_CODES + '))',
    'g',
  )

  /** Every money-looking substring of `text`, left to right. */
  function findMoney(text, fallbackCurrency) {
    var out = []
    if (!text) return out
    MONEY_RE.lastIndex = 0
    var m
    while ((m = MONEY_RE.exec(text))) {
      var raw = m[0]
      // "$5 off 20% today" — a trailing % means it was never an amount.
      if (text.charAt(m.index + raw.length) === '%') continue
      var money = parseMoney(raw, fallbackCurrency)
      if (!money) continue
      if (money.amount_minor <= 0) continue
      if (money.amount_minor > 1e13) continue
      out.push({ raw: raw.trim(), index: m.index, money: money })
      if (out.length > 200) break
    }
    return out
  }

  // ---------------------------------------------------------------------
  // Small DOM helpers (kept to the intersection of every DOM impl we run on)
  // ---------------------------------------------------------------------

  function qsa(root, sel) {
    try {
      return Array.prototype.slice.call(root.querySelectorAll(sel))
    } catch (e) {
      return []
    }
  }
  function attr(el, name) {
    try {
      var v = el.getAttribute(name)
      return v === null || v === undefined ? null : String(v).trim()
    } catch (e) {
      return null
    }
  }
  function text(el, max) {
    try {
      var t = (el.textContent || '').replace(/\s+/g, ' ').trim()
      return max ? t.slice(0, max) : t
    } catch (e) {
      return ''
    }
  }
  function meta(doc, names) {
    for (var i = 0; i < names.length; i++) {
      var n = names[i].replace(/"/g, '')
      var el =
        doc.querySelector('meta[property="' + n + '"]') ||
        doc.querySelector('meta[name="' + n + '"]') ||
        doc.querySelector('meta[itemprop="' + n + '"]')
      if (el) {
        var c = attr(el, 'content')
        if (c) return c
      }
    }
    return null
  }
  function clean(s, max) {
    if (s === null || s === undefined) return null
    var t = String(s).replace(/\s+/g, ' ').trim()
    return t ? t.slice(0, max || 200) : null
  }
  function firstString(v) {
    if (v === null || v === undefined) return null
    if (typeof v === 'string') return clean(v)
    if (typeof v === 'number') return String(v)
    if (Array.isArray(v)) {
      for (var i = 0; i < v.length; i++) {
        var s = firstString(v[i])
        if (s) return s
      }
      return null
    }
    if (typeof v === 'object') return firstString(v.name || v['@id'] || v.url || v.value)
    return null
  }
  function typesOf(node) {
    var t = node && node['@type']
    if (!t) return []
    return (Array.isArray(t) ? t : [t]).map(function (x) {
      return String(x).replace(/^https?:\/\/schema\.org\//, '')
    })
  }

  // ---------------------------------------------------------------------
  // Strategy a — JSON-LD
  // ---------------------------------------------------------------------

  var EVENT_TYPES = [
    'Event', 'MusicEvent', 'TheaterEvent', 'ScreeningEvent', 'SportsEvent',
    'Festival', 'BusinessEvent', 'ComedyEvent', 'DanceEvent', 'EducationEvent',
    'ExhibitionEvent', 'LiteraryEvent', 'SocialEvent', 'FoodEvent',
    'ChildrensEvent', 'PublicationEvent', 'CourseInstance', 'EventSeries',
  ]
  var PRODUCT_TYPES = [
    'Product', 'ProductGroup', 'IndividualProduct', 'SomeProducts', 'Vehicle',
    'Car', 'ProductModel', 'Book', 'MusicAlbum', 'MusicRelease', 'Movie',
    'VideoGame', 'SoftwareApplication', 'Service', 'MenuItem', 'Course',
    'TouristAttraction', 'Hotel', 'LodgingBusiness', 'Trip', 'Flight',
  ]
  var ORDER_TYPES = ['Order', 'Invoice', 'ParcelDelivery']
  var OFFER_TYPES = ['Offer', 'AggregateOffer', 'Demand']

  // Where to keep looking when a node isn't itself a match.
  var RECURSE_KEYS = [
    '@graph', 'mainEntity', 'mainEntityOfPage', 'itemListElement', 'item',
    'hasVariant', 'isVariantOf', 'about', 'subjectOf', 'workExample',
    'albumRelease', 'releaseOf', 'offers', 'makesOffer', 'orderedItem',
    'acceptedOffer', 'itemOffered', 'subEvent', 'superEvent', 'hasPart',
    'includesObject', 'model', 'isRelatedTo',
  ]

  function jsonLdBlocks(doc, warnings) {
    var out = []
    var scripts = qsa(doc, 'script')
    for (var i = 0; i < scripts.length; i++) {
      var type = (attr(scripts[i], 'type') || '').toLowerCase()
      if (type.indexOf('ld+json') === -1) continue
      var raw = (scripts[i].textContent || '').trim()
      if (!raw) continue
      raw = raw
        .replace(/^<!--/, '').replace(/-->$/, '')
        .replace(/^\s*\/\*\s*<!\[CDATA\[\s*\*\//, '')
        .replace(/\/\*\s*\]\]>\s*\*\/\s*$/, '')
        .trim()
      var parsed = tryJson(raw)
      if (parsed === undefined) parsed = tryJson(raw.replace(/,\s*([}\]])/g, '$1'))
      if (parsed === undefined) {
        // Some CMSes emit several top-level objects back to back.
        var chunks = raw.split(/}\s*{/)
        if (chunks.length > 1) {
          for (var c = 0; c < chunks.length; c++) {
            var piece = (c === 0 ? '' : '{') + chunks[c] + (c === chunks.length - 1 ? '' : '}')
            var p = tryJson(piece)
            if (p !== undefined) out.push(p)
          }
          continue
        }
        if (warnings) warnings.push('a JSON-LD block on this page did not parse')
        continue
      }
      out.push(parsed)
    }
    return out
  }
  function tryJson(s) {
    try {
      return JSON.parse(s)
    } catch (e) {
      return undefined
    }
  }

  function collect(value, want, acc, depth) {
    acc = acc || []
    depth = depth || 0
    if (depth > 12 || acc.length > 400) return acc
    if (Array.isArray(value)) {
      for (var i = 0; i < value.length; i++) collect(value[i], want, acc, depth + 1)
      return acc
    }
    if (!value || typeof value !== 'object') return acc
    var types = typesOf(value)
    for (var t = 0; t < types.length; t++) {
      if (want.indexOf(types[t]) !== -1) {
        acc.push(value)
        break
      }
    }
    for (var k = 0; k < RECURSE_KEYS.length; k++) {
      var key = RECURSE_KEYS[k]
      if (value[key]) collect(value[key], want, acc, depth + 1)
    }
    return acc
  }

  /** Offer | AggregateOffer | PriceSpecification | array -> price candidate. */
  function offerPrice(offers, fallbackCurrency, warnings) {
    if (!offers) return null
    if (Array.isArray(offers)) {
      var best = null
      for (var i = 0; i < offers.length; i++) {
        var p = offerPrice(offers[i], fallbackCurrency, warnings)
        if (p && (!best || p.amount_minor < best.amount_minor)) best = p
      }
      return best
    }
    if (typeof offers !== 'object') return null
    var cur =
      firstString(offers.priceCurrency) ||
      firstString(offers.priceSpecification && offers.priceSpecification.priceCurrency) ||
      fallbackCurrency
    var types = typesOf(offers)

    var raw = offers.price
    if (raw === undefined || raw === null || raw === '') {
      if (offers.priceSpecification) {
        var ps = Array.isArray(offers.priceSpecification) ? offers.priceSpecification[0] : offers.priceSpecification
        if (ps) {
          raw = ps.price
          cur = firstString(ps.priceCurrency) || cur
        }
      }
    }
    if ((raw === undefined || raw === null || raw === '') && offers.lowPrice !== undefined) {
      raw = offers.lowPrice
      if (warnings && types.indexOf('AggregateOffer') !== -1) {
        warnings.push('this page lists a price range — used the lowest (' + firstString(offers.lowPrice) + ')')
      }
    }
    if (raw === undefined || raw === null || raw === '') {
      // Offer wrapping another Offer / itemOffered with its own offers.
      if (offers.offers) return offerPrice(offers.offers, cur, warnings)
      if (offers.itemOffered && offers.itemOffered.offers) return offerPrice(offers.itemOffered.offers, cur, warnings)
      return null
    }
    var m = parseMoney(raw, cur, { structured: true })
    if (!m) return null
    if (m.amount_minor <= 0) return null
    return m
  }

  function nodeUrl(node) {
    return firstString(node.url) || firstString(node['@id']) || null
  }

  /** Prefer the node that is actually about *this* URL. */
  function pickForPage(nodes, loc) {
    if (nodes.length <= 1) return { node: nodes[0] || null, ambiguous: false }
    var href = ''
    var path = ''
    try {
      href = String(loc.href || '').split('#')[0]
      path = String(loc.pathname || '')
    } catch (e) {}
    for (var i = 0; i < nodes.length; i++) {
      var u = nodeUrl(nodes[i])
      if (!u) continue
      var normalized = u.split('#')[0].split('?')[0]
      if (href && (normalized === href.split('?')[0] || href.indexOf(normalized) === 0)) {
        return { node: nodes[i], ambiguous: false }
      }
      if (path && path.length > 1 && normalized.slice(-path.length) === path) {
        return { node: nodes[i], ambiguous: false }
      }
    }
    return { node: nodes[0], ambiguous: true }
  }

  function fromJsonLd(doc, loc, ctx) {
    var warnings = []
    var docs = jsonLdBlocks(doc, warnings)
    if (!docs.length) return null

    var orders = collect(docs, ORDER_TYPES)
    var products = collect(docs, PRODUCT_TYPES)
    var events = collect(docs, EVENT_TYPES)
    var offers = collect(docs, OFFER_TYPES)
    if (!orders.length && !products.length && !events.length && !offers.length) return null

    var cand = { source: 'json-ld', warnings: warnings, items: [], fees: [] }
    var fallbackCur = ctx.weakCurrency

    // -- Order: the strongest signal there is. A real basket.
    if (orders.length) {
      var order = orders[0]
      var lines = order.orderedItem
        ? Array.isArray(order.orderedItem) ? order.orderedItem : [order.orderedItem]
        : []
      var orderCur =
        firstString(order.priceCurrency) ||
        firstString(order.totalPaymentDue && order.totalPaymentDue.priceCurrency) ||
        fallbackCur
      for (var i = 0; i < lines.length; i++) {
        var line = lines[i]
        var prod = line.orderedItem || line.itemOffered || line
        var lp = offerPrice(line.acceptedOffer || prod.offers, orderCur, warnings)
        var qty = Number(firstString(line.orderQuantity) || firstString(line.eligibleQuantity) || 1) || 1
        if (lp) {
          cand.items.push({
            name: firstString(prod.name) || firstString(line.name) || 'Item ' + (i + 1),
            unit_amount: lp.amount_minor,
            qty: Math.max(1, Math.round(qty)),
            sku: firstString(prod.sku) || firstString(prod.productID) || null,
          })
          orderCur = lp.currency
        }
      }
      var due = order.totalPaymentDue
      var total = due ? parseMoney(firstString(due.price) || due.price, firstString(due.priceCurrency) || orderCur, { structured: true }) : null
      cand.title = firstString(order.name) || (order.orderNumber ? 'Order ' + firstString(order.orderNumber) : null)
      cand.currency = (total && total.currency) || orderCur
      cand.total_minor = total ? total.amount_minor : null
      cand.merchantName = firstString(order.seller) || firstString(order.merchant) || firstString(order.broker)
      cand.kind = 'order'
      cand.confidence = 0.95
      if (cand.items.length || cand.total_minor) return cand
    }

    // -- Event (a showing, a gig, a screening) — the ticket case.
    var chosen = null
    var kind = null
    var ambiguous = false
    var siblings = 0
    if (events.length) {
      var pe = pickForPage(events, loc)
      chosen = pe.node
      ambiguous = pe.ambiguous
      siblings = events.length
      kind = 'event'
      if (events.length > 3 && ambiguous) {
        warnings.push('this page describes ' + events.length + ' events — picked the first one')
      }
    }
    if (!chosen && products.length) {
      var pp = pickForPage(products, loc)
      chosen = pp.node
      ambiguous = pp.ambiguous
      siblings = products.length
      kind = 'product'
      if (products.length > 3 && ambiguous) {
        warnings.push('this page describes ' + products.length + ' products — picked the first one')
      }
    }
    if (!chosen && offers.length) {
      chosen = offers[0]
      kind = 'offer'
    }
    if (!chosen) return null

    var price = null
    if (kind === 'offer') {
      price = offerPrice(chosen, fallbackCur, warnings)
    } else {
      price = offerPrice(chosen.offers, fallbackCur, warnings)
      if (!price && chosen.hasVariant) price = offerPrice(collect(chosen.hasVariant, PRODUCT_TYPES).map(function (v) { return v.offers }), fallbackCur, warnings)
      if (!price && chosen.albumRelease) price = offerPrice(collect(chosen.albumRelease, ['MusicRelease', 'Product']).map(function (v) { return v.offers }), fallbackCur, warnings)
      if (!price && offers.length) price = offerPrice(offers[0], fallbackCur, warnings)
    }

    cand.kind = kind
    cand.title = firstString(chosen.name) || firstString(chosen.headline) || null
    cand.image = firstString(chosen.image) || null
    cand.merchantName =
      firstString(chosen.seller) ||
      firstString(chosen.organizer) ||
      firstString(chosen.brand) ||
      firstString(chosen.offers && chosen.offers.seller) ||
      null

    if (kind === 'event') {
      var place = chosen.location
      if (Array.isArray(place)) place = place[0]
      cand.event = {
        start: firstString(chosen.startDate) || null,
        end: firstString(chosen.endDate) || null,
        venue: place ? firstString(place.name) || firstString(place.address) : null,
        address: place && place.address ? addressLine(place.address) : null,
      }
    }

    if (price) {
      cand.currency = price.currency
      cand.items.push({
        name: cand.title || (kind === 'event' ? 'Ticket' : 'Item'),
        unit_amount: price.amount_minor,
        qty: 1,
        sku: firstString(chosen.sku) || firstString(chosen.productID) || firstString(chosen.mpn) || null,
      })
      cand.total_minor = price.amount_minor
      cand.confidence = kind === 'offer' ? 0.82 : 0.9
      // Nothing on the page said which of these the page is *about*. On a
      // search results page that is a coin flip, not a detection.
      //
      // The penalty scales with how many things we were choosing between: a
      // real 309-listing Craigslist page was landing on 0.6 and being labelled
      // "good confidence", which is a coin flip wearing a reassuring word. Two
      // candidates is a mild doubt; three hundred is not a detection at all.
      if (ambiguous) {
        var spread = Math.min(0.45, 0.12 + 0.13 * Math.log2(Math.max(2, siblings)))
        cand.confidence -= spread
      }
    } else {
      // Name but no price is still worth having — og/DOM may fill the number.
      cand.confidence = 0.4
      warnings.push('structured data named the item but carried no price')
    }
    return cand
  }

  function addressLine(a) {
    if (!a) return null
    if (typeof a === 'string') return clean(a)
    var parts = [a.streetAddress, a.addressLocality, a.addressRegion, a.postalCode, a.addressCountry]
      .map(firstString)
      .filter(Boolean)
    return parts.length ? clean(parts.join(', ')) : null
  }

  // ---------------------------------------------------------------------
  // Strategy b — microdata
  // ---------------------------------------------------------------------

  /** Read itemprops belonging to `scope`, not to any nested itemscope. */
  function scopedProp(scope, prop) {
    var all = qsa(scope, '[itemprop~="' + prop + '"]')
    for (var i = 0; i < all.length; i++) {
      var el = all[i]
      var owner = el.parentElement
      var mine = true
      while (owner && owner !== scope) {
        if (owner.hasAttribute && owner.hasAttribute('itemscope')) { mine = false; break }
        owner = owner.parentElement
      }
      if (!mine) continue
      var v =
        attr(el, 'content') ||
        attr(el, 'datetime') ||
        (el.tagName === 'META' ? null : attr(el, 'href') || attr(el, 'src')) ||
        text(el, 300)
      if (v) return v
    }
    return null
  }

  function fromMicrodata(doc, loc, ctx) {
    var scopes = qsa(
      doc,
      '[itemscope][itemtype*="schema.org/Product"],[itemscope][itemtype*="schema.org/Event"],' +
      '[itemscope][itemtype*="schema.org/Offer"],[itemscope][itemtype*="schema.org/Order"]',
    )
    if (!scopes.length) return null
    var warnings = []
    for (var i = 0; i < scopes.length && i < 8; i++) {
      var scope = scopes[i]
      var name = scopedProp(scope, 'name')
      var priceRaw = scopedProp(scope, 'price') || scopedProp(scope, 'lowPrice')
      var cur = scopedProp(scope, 'priceCurrency')
      if (!priceRaw) {
        var nested = qsa(scope, '[itemprop~="offers"]')[0]
        if (nested) {
          priceRaw = scopedProp(nested, 'price') || scopedProp(nested, 'lowPrice')
          cur = cur || scopedProp(nested, 'priceCurrency')
        }
      }
      if (!priceRaw && !name) continue
      var money = priceRaw ? parseMoney(priceRaw, cur || ctx.weakCurrency, { structured: true }) : null
      if (!money && !name) continue
      var avail = scopedProp(scope, 'availability')
      if (avail && /OutOfStock|SoldOut|Discontinued/i.test(avail)) warnings.push('microdata says this item is out of stock')
      return {
        source: 'microdata',
        kind: 'product',
        title: name,
        image: scopedProp(scope, 'image'),
        currency: money ? money.currency : cur || null,
        total_minor: money ? money.amount_minor : null,
        items: money
          ? [{ name: name || 'Item', unit_amount: money.amount_minor, qty: 1, sku: scopedProp(scope, 'sku') }]
          : [],
        fees: [],
        confidence: money ? 0.78 : 0.35,
        warnings: warnings,
      }
    }
    return null
  }

  // ---------------------------------------------------------------------
  // Strategy c — OpenGraph / meta
  // ---------------------------------------------------------------------

  function fromMeta(doc, loc, ctx) {
    var warnings = []
    var title =
      meta(doc, ['og:title', 'twitter:title']) ||
      clean(doc.title) ||
      (doc.querySelector('h1') ? text(doc.querySelector('h1'), 140) : null)
    var image = meta(doc, ['og:image:secure_url', 'og:image', 'twitter:image', 'twitter:image:src'])
    var site = meta(doc, ['og:site_name', 'application-name'])

    var amount = meta(doc, [
      'product:price:amount', 'og:price:amount', 'product:sale_price:amount',
      'twitter:data1', 'price',
    ])
    var currency = meta(doc, [
      'product:price:currency', 'og:price:currency', 'product:sale_price:currency', 'priceCurrency',
    ])

    // twitter:data1 is a free-form slot — eventbrite puts the *address* in it.
    // Only trust it if its label says price, or the value is unmistakably money.
    var fromData1 = amount !== null && amount === meta(doc, ['twitter:data1'])
    if (fromData1) {
      var label = meta(doc, ['twitter:label1']) || ''
      var looksLikeMoney = !!currencyFromString(amount) && /\d/.test(amount)
      if (!/price|cost|from|amount|fee|ticket/i.test(label) && !looksLikeMoney) amount = null
      else if (looksLikeMoney && !/price|cost|from|amount|fee|ticket/i.test(label)) {
        warnings.push('price came from twitter:data1, which merchants use for anything')
      }
    }

    var money = amount ? parseMoney(amount, currency || ctx.weakCurrency, { structured: true }) : null
    if (money && money.amount_minor <= 0) money = null

    if (!title && !money) return null
    return {
      source: 'og',
      kind: 'product',
      title: title,
      image: image,
      merchantName: site,
      currency: money ? money.currency : currency || null,
      total_minor: money ? money.amount_minor : null,
      items: money ? [{ name: title || 'Item', unit_amount: money.amount_minor, qty: 1, sku: null }] : [],
      fees: [],
      confidence: money ? 0.66 : 0.2,
      warnings: warnings,
    }
  }

  // ---------------------------------------------------------------------
  // Strategy d — Shopify
  // ---------------------------------------------------------------------

  function isShopify(doc, win) {
    try {
      if (win && (win.Shopify || win.ShopifyAnalytics)) return true
    } catch (e) {}
    if (doc.querySelector('link[href*="cdn.shopify.com"],script[src*="cdn.shopify.com"],img[src*="cdn.shopify.com"]')) return true
    if (doc.querySelector('meta[name="shopify-checkout-api-token"],meta[name="shopify-digital-wallet"]')) return true
    return false
  }

  /** window.ShopifyAnalytics.meta — synchronous, no network. */
  function fromShopifyMeta(doc, loc, ctx) {
    var win = ctx.win
    var m = null
    try {
      m = (win.ShopifyAnalytics && win.ShopifyAnalytics.meta) || (win.meta && win.meta.product ? win.meta : null)
    } catch (e) {}
    if (!m || !m.product) return null
    var p = m.product
    var currency = null
    try {
      currency = m.currency || (win.Shopify && win.Shopify.currency && win.Shopify.currency.active) || null
    } catch (e) {}
    currency = currency || ctx.weakCurrency || 'USD'

    var variants = p.variants || []
    var selected = null
    if (m.selectedVariantId) {
      for (var i = 0; i < variants.length; i++) {
        if (String(variants[i].id) === String(m.selectedVariantId)) { selected = variants[i]; break }
      }
    }
    selected = selected || variants[0]
    if (!selected) return null
    // Shopify prices in `meta` are already integer minor units.
    var unit = Math.round(Number(selected.price))
    if (!isFinite(unit) || unit <= 0) return null
    return {
      source: 'shopify-meta',
      kind: 'product',
      title: clean(selected.name || p.title || p.handle),
      merchantName: clean(p.vendor),
      currency: String(currency).toUpperCase(),
      total_minor: unit,
      items: [{ name: clean(selected.name || p.title) || 'Item', unit_amount: unit, qty: 1, sku: clean(selected.sku) || null }],
      fees: [],
      confidence: 0.86,
      warnings: [],
    }
  }

  /** GET /cart.js — the customer's REAL current basket. */
  function fromShopifyCart(doc, loc, ctx) {
    var f = ctx.fetch
    if (!f) return Promise.resolve(null)
    var origin = ''
    try {
      origin = loc.origin || (loc.protocol + '//' + loc.host)
    } catch (e) {
      return Promise.resolve(null)
    }
    var url = origin + '/cart.js'
    var timer = null
    var opts = { credentials: 'include', headers: { accept: 'application/json' } }
    try {
      if (typeof AbortController === 'function') {
        var ac = new AbortController()
        opts.signal = ac.signal
        timer = setTimeout(function () { try { ac.abort() } catch (e) {} }, ctx.timeoutMs || 3500)
      }
    } catch (e) {}

    return Promise.resolve()
      .then(function () { return f(url, opts) })
      .then(function (res) {
        if (!res || !res.ok) return null
        return res.json()
      })
      .then(function (cart) {
        if (timer) clearTimeout(timer)
        if (!cart || !cart.items || !cart.items.length) return null
        var currency = String(cart.currency || ctx.weakCurrency || 'USD').toUpperCase()
        var items = []
        for (var i = 0; i < cart.items.length; i++) {
          var it = cart.items[i]
          var unit = Math.round(Number(it.final_price !== undefined ? it.final_price : it.price))
          if (!isFinite(unit)) continue
          items.push({
            name: clean(it.product_title && it.variant_title && it.variant_title !== 'Default Title'
              ? it.product_title + ' — ' + it.variant_title
              : it.title || it.product_title) || 'Item',
            unit_amount: unit,
            qty: Math.max(1, Math.round(Number(it.quantity) || 1)),
            sku: clean(it.sku) || (it.variant_id ? 'shopify-' + it.variant_id : null),
            image: it.image || null,
          })
        }
        if (!items.length) return null
        var total = Math.round(Number(cart.total_price))
        return {
          source: 'shopify-cart',
          kind: 'cart',
          title: items.length === 1 ? items[0].name : items.length + ' items in your cart',
          currency: currency,
          total_minor: isFinite(total) ? total : null,
          items: items,
          fees: [],
          confidence: 0.97,
          warnings: [],
        }
      })
      .catch(function () {
        if (timer) clearTimeout(timer)
        return null
      })
  }

  // ---------------------------------------------------------------------
  // Strategy e — DOM total heuristic (last resort)
  // ---------------------------------------------------------------------

  var TOTAL_LABELS = [
    [/\bgrand\s*total\b/i, 100],
    [/\border\s*total\b/i, 96],
    [/\btotal\s*(?:amount\s*)?due\b/i, 94],
    [/\bamount\s*due\b/i, 92],
    [/\bamount\s*payable\b/i, 90],
    [/\btotal\s*payable\b/i, 90],
    [/\bestimated\s*total\b/i, 84],
    [/\btotal\s*price\b/i, 80],
    [/\btotal\s*cost\b/i, 78],
    [/\byou\s*pay\b/i, 76],
    [/\bto\s*pay\b/i, 74],
    [/\bcart\s*total\b/i, 88],
    [/\btotal\b/i, 60],
    [/\bpayable\b/i, 58],
    [/\bsub\s*-?\s*total\b/i, 30],
  ]
  var SKIP_TAGS = { SCRIPT: 1, STYLE: 1, NOSCRIPT: 1, TEMPLATE: 1, SVG: 1, HEAD: 1, IFRAME: 1, CANVAS: 1, SELECT: 1 }

  function countWords(s) {
    var m = String(s).trim().match(/[^\s]+/g)
    return m ? m.length : 0
  }

  /** Best-scoring total label in `s`, with where it sits. */
  function labelHit(s) {
    var best = null
    for (var i = 0; i < TOTAL_LABELS.length; i++) {
      TOTAL_LABELS[i][0].lastIndex = 0
      var m = TOTAL_LABELS[i][0].exec(s)
      if (!m) continue
      var score = TOTAL_LABELS[i][1]
      // Sub-total must never be scored as "total".
      if (/\btotal\b/i.test(m[0]) && /\bsub\s*-?\s*total\b/i.test(s) && score > 30) {
        var subIdx = s.search(/\bsub\s*-?\s*total\b/i)
        if (subIdx !== -1 && Math.abs(subIdx - m.index) < 12) score = 30
      }
      if (!best || score > best.score) best = { score: score, index: m.index, length: m[0].length }
    }
    return best
  }

  function isHidden(el) {
    try {
      if (el.hasAttribute && (el.hasAttribute('hidden') || el.getAttribute('aria-hidden') === 'true')) return true
      var st = el.getAttribute && el.getAttribute('style')
      if (st && /display\s*:\s*none|visibility\s*:\s*hidden/i.test(st)) return true
    } catch (e) {}
    return false
  }

  /** Depth-first text-node walk that respects SKIP_TAGS and hidden nodes. */
  function walkText(root, visit, budget) {
    var stack = [root]
    var seen = 0
    while (stack.length) {
      var n = stack.pop()
      if (!n) continue
      if (n.nodeType === 3) {
        var t = n.nodeValue
        if (t && t.trim()) {
          if (++seen > (budget || 12000)) return
          visit(n, t)
        }
        continue
      }
      if (n.nodeType !== 1) continue
      if (SKIP_TAGS[n.tagName]) continue
      if (isHidden(n)) continue
      var kids = n.childNodes
      for (var i = kids.length - 1; i >= 0; i--) stack.push(kids[i])
    }
  }

  function rowFor(node) {
    var el = node.parentElement
    var hops = 0
    var best = el
    while (el && hops < 5) {
      var tag = el.tagName
      var cls = (attr(el, 'class') || '').toLowerCase()
      if (tag === 'TR' || tag === 'LI' || tag === 'DL' ||
          /(^|[\s_-])(total|summary|order[-_]?total|grand|amount|price|row|line)([\s_-]|$)/.test(cls)) {
        return el
      }
      best = el
      el = el.parentElement
      hops++
    }
    return best
  }

  /**
   * The price next to the buy button.
   *
   * `fromDomTotal` anchors on words like "Total" and "Amount due", which only
   * exist on a CHECKOUT. A product page has no total — it has a price and a
   * button that says "Add to Cart". So on Amazon, and on every other store
   * whose price is rendered by JavaScript rather than published as markup,
   * every other strategy returns nothing and this one is the only thing left.
   *
   * Deliberately generic rather than a per-site adapter: the anchor is the buy
   * ACTION, which every product page on the internet has, in whatever markup
   * its authors felt like. Confidence stays low and the warning always names
   * the button it anchored on, because this is a read off rendered text, not a
   * fact the merchant published.
   *
   * Only useful in a real browser — running against fetched HTML, the price is
   * usually still an empty div waiting for JavaScript. That is exactly why the
   * extension can do this and pasting a link cannot.
   */
  var BUY_LABELS = /\b(?:add to (?:cart|bag|basket)|buy (?:it )?now|add to trolley|proceed to (?:buy|checkout)|pre-?order now)\b/i

  /**
   * Text that marks a nearby amount as something OTHER than what you would
   * pay: the crossed-out original, the discount, the free-shipping threshold.
   * On a discounted product the list price is the biggest number on the page,
   * so without this the group gets billed the pre-sale price.
   */
  var NOT_THE_PRICE =
    /(?:\blist\s*price\b|\bwas\b|\brrp\b|\bmrp\b|m\.r\.p|\borig(?:inal)?\b|\byou\s*save\b|\bsave\b|\bsavings?\b|\bdiscount\b|\btypical\s*price\b|\bcompare\s*at\b|\bfree\s*(?:shipping|delivery)\b|\borders?\s*over\b|\bspend\b|\bpayments?\s*of\b|\bmonthly\b|\bemi\b|\bper\s*month\b|\/\s*mo\b|\binstal?ments?\b|\bfrom\s*$)/i

  function fromBuyAction(doc, loc, ctx) {
    var body = doc.body
    if (!body) return null
    var buttons = qsa(body, 'button, input[type=submit], a[role=button], [data-action], .a-button-input')
    var anchor = null
    for (var i = 0; i < buttons.length && i < 400; i++) {
      var label = text(buttons[i], 60) || attr(buttons[i], 'value') || attr(buttons[i], 'aria-label') || ''
      if (BUY_LABELS.test(label)) { anchor = { el: buttons[i], label: label.trim() }; break }
    }
    if (!anchor) return null

    // Climb from the button until the surrounding block contains money, but
    // not so far that the whole page counts as "near the button".
    var el = anchor.el
    var hops = 0
    while (el && hops < 7) {
      var blob = text(el, 1200)
      var found = findMoney(blob, ctx.weakCurrency)
      if (found.length) {
        // Drop the amounts that are explicitly NOT what you would pay. A
        // struck-through list price is usually the largest number on a
        // product page, so picking "the biggest one near the button" would
        // reliably overcharge the group on anything discounted.
        var live = []
        for (var f = 0; f < found.length; f++) {
          // The window has to stop at the previous amount. Running a flat 44
          // characters back made "M.R.P: ₹34,990  ₹24,990" reject the sale
          // price too, because the previous label was still inside the window
          // — leaving only the instalment line as a candidate.
          var floor = f > 0 ? found[f - 1].index + found[f - 1].raw.length : 0
          var around = blob.slice(Math.max(floor, found[f].index - 44), found[f].index)
          if (NOT_THE_PRICE.test(around)) continue
          live.push(found[f])
        }
        if (!live.length) { el = el.parentElement; hops++; continue }

        // Of what remains, the one physically nearest the button. Instalment
        // lines ("4 payments of $27.50") and shipping thresholds sit further
        // out; the price sits against the button.
        var best = live[0]
        for (var g = 1; g < live.length; g++) {
          if (live[g].index < best.index) best = live[g]
        }
        if (best.money.amount_minor <= 0) return null
        var name = clean(doc.title) || meta(doc, ['og:title']) || 'Item'
        return {
          source: 'buy-action',
          kind: 'dom',
          title: name,
          currency: best.money.currency,
          total_minor: best.money.amount_minor,
          items: [{ name: name, unit_amount: best.money.amount_minor, qty: 1, sku: null }],
          fees: [],
          confidence: found.length > 6 ? 0.28 : 0.36,
          warnings: [
            'this page publishes no machine-readable price, so this was read off the text beside the "' +
              anchor.label.slice(0, 28) +
              '" button — check it before you split',
          ],
          label: anchor.label.slice(0, 40),
        }
      }
      el = el.parentElement
      hops++
    }
    return null
  }

  function fromDomTotal(doc, loc, ctx) {
    var body = doc.body
    if (!body) return null
    var candidates = []
    var fallbackCur = ctx.weakCurrency

    walkText(body, function (node, raw) {
      var s = raw.replace(/\s+/g, ' ').trim()
      if (s.length > 300) return
      var hit = labelHit(s)
      if (!hit) return
      var score = hit.score

      // Prose guards. "…the total operating revenue was $1.7 billion…" is a
      // sentence, not a checkout line. A total label sits in a short cell,
      // near the front of it, with its number right next to it.
      if (countWords(s) > 12) return
      if (countWords(s.slice(0, hit.index)) > 4) return

      // 1. money in the same text node, right after the label
      var here = findMoney(s, fallbackCur)
      if (here.length) {
        var after = null
        for (var h = 0; h < here.length; h++) {
          if (here[h].index >= hit.index) { after = here[h]; break }
        }
        if (!after) return
        if (after.index - (hit.index + hit.length) > 40) return
        candidates.push({ score: score + 6, money: here[here.length - 1].money, why: s.slice(0, 80), distance: 0 })
        return
      }
      // 2. money in the enclosing row / summary line
      var row = rowFor(node)
      if (!row) return
      var rowText = text(row, 600)
      if (!rowText) return
      // A huge container means we would be grabbing an unrelated number.
      if (rowText.length > 220 || countWords(rowText) > 24) return
      var found = findMoney(rowText, fallbackCur)
      if (!found.length) return
      candidates.push({
        score: score - 4,
        money: found[found.length - 1].money,
        why: rowText.slice(0, 90),
        distance: rowText.length,
      })
    })

    if (!candidates.length) return null
    candidates.sort(function (a, b) {
      if (b.score !== a.score) return b.score - a.score
      return a.distance - b.distance
    })
    var top = candidates[0]
    if (top.score < 55) return null // subtotal-only pages: not good enough

    var conf = top.score >= 90 ? 0.45 : top.score >= 74 ? 0.38 : 0.3
    var warnings = ['this number was read off the page text ("' + top.why.trim() + '") — check it before you split']
    // Several different totals on one page is a red flag.
    var distinct = {}
    for (var i = 0; i < candidates.length && i < 12; i++) distinct[candidates[i].money.amount_minor] = 1
    var n = 0
    for (var k in distinct) if (Object.prototype.hasOwnProperty.call(distinct, k)) n++
    if (n > 3) {
      conf -= 0.08
      warnings.push('found ' + n + ' different total-ish amounts on this page')
    }

    var title = clean(doc.title) || meta(doc, ['og:title']) || 'Order'
    return {
      source: 'dom-total',
      kind: 'dom',
      title: title,
      currency: top.money.currency,
      total_minor: top.money.amount_minor,
      items: [{ name: null, unit_amount: top.money.amount_minor, qty: 1, sku: null }],
      fees: [],
      confidence: Math.max(0.18, conf),
      warnings: warnings,
      label: top.why.trim(),
    }
  }

  // ---------------------------------------------------------------------
  // Strategy f — what the user actually highlighted
  // ---------------------------------------------------------------------

  function fromSelection(doc, loc, ctx) {
    var sel = null
    try {
      sel = ctx.selectionText !== undefined ? ctx.selectionText : (ctx.win.getSelection ? String(ctx.win.getSelection()) : '')
    } catch (e) {
      return null
    }
    if (!sel) return null
    sel = sel.replace(/\s+/g, ' ').trim()
    if (!sel || sel.length > 400) return null
    var found = findMoney(sel, ctx.weakCurrency)
    if (!found.length) return null
    // If they highlighted a range, take the largest — people select the total.
    var money = found[0].money
    for (var i = 1; i < found.length; i++) if (found[i].money.amount_minor > money.amount_minor) money = found[i].money
    var label = sel.replace(found[0].raw, '').replace(/\s+/g, ' ').trim()
    return {
      source: 'selection',
      kind: 'selection',
      title: label && label.length > 2 ? clean(label, 90) : null,
      currency: money.currency,
      total_minor: money.amount_minor,
      items: [{ name: clean(label, 90) || 'Selected amount', unit_amount: money.amount_minor, qty: 1, sku: null }],
      fees: [],
      confidence: 0.75,
      warnings: ['using the amount you highlighted on the page'],
    }
  }

  // ---------------------------------------------------------------------
  // Merge
  // ---------------------------------------------------------------------

  // Highest authority first. `selection` outranks everything for the *number*
  // because it is the one signal a human deliberately gave us.
  var PRIORITY = ['selection', 'shopify-cart', 'json-ld', 'shopify-meta', 'microdata', 'og', 'dom-total', 'buy-action']

  function merge(cands, doc, loc, ctx) {
    cands = cands.filter(Boolean)
    cands.sort(function (a, b) {
      return PRIORITY.indexOf(a.source) - PRIORITY.indexOf(b.source)
    })

    var out = {
      title: null,
      kind: null,
      merchant: merchantOf(doc, loc, cands),
      currency: null,
      items: [],
      fees: [],
      total_minor: null,
      confidence: 0,
      strategy: [],
      provenance: {},
      warnings: [],
      page_url: safeHref(loc),
      image: null,
      event: null,
      detected_at: new Date().toISOString(),
      version: VERSION,
    }
    if (!cands.length) {
      out.warnings.push('nothing on this page looked like a cart, a product or an order')
      return out
    }

    var used = {}
    function take(field, value, source) {
      if (out[field] !== null && out[field] !== undefined && out[field] !== '') return
      if (value === null || value === undefined || value === '') return
      out[field] = value
      out.provenance[field] = source
      used[source] = 1
    }

    // Money first: whichever candidate owns the amount also owns the currency
    // and the line items, so the three never come from different worlds.
    var moneyOwner = null
    for (var i = 0; i < cands.length; i++) {
      if (cands[i].total_minor !== null && cands[i].total_minor !== undefined) { moneyOwner = cands[i]; break }
    }
    if (moneyOwner) {
      out.total_minor = moneyOwner.total_minor
      out.kind = moneyOwner.kind || null
      out.currency = moneyOwner.currency || null
      out.provenance.total_minor = moneyOwner.source
      out.provenance.currency = moneyOwner.source
      used[moneyOwner.source] = 1
      if (moneyOwner.items && moneyOwner.items.length) {
        out.items = moneyOwner.items.map(function (it) {
          return {
            name: it.name || 'Item',
            unit_amount: it.unit_amount,
            qty: it.qty || 1,
            sku: it.sku || null,
            image: it.image || null,
          }
        })
        out.provenance.items = moneyOwner.source
      }
      if (moneyOwner.fees && moneyOwner.fees.length) {
        out.fees = moneyOwner.fees
        out.provenance.fees = moneyOwner.source
      }
    }

    for (var j = 0; j < cands.length; j++) {
      var c = cands[j]
      take('title', c.title, c.source)
      take('image', c.image, c.source)
      take('event', c.event, c.source)
      take('kind', c.kind, c.source)
      if (!out.currency && c.currency) take('currency', c.currency, c.source)
      if (c.merchantName && !out.merchant.name_from_data) {
        out.merchant.name = c.merchantName
        out.merchant.name_from_data = true
        out.provenance.merchant = c.source
        used[c.source] = 1
      }
    }
    delete out.merchant.name_from_data

    // Only surface warnings from strategies that actually shaped the answer.
    // A DOM-scrape caveat on a page whose price came from JSON-LD is noise.
    for (var y = 0; y < cands.length; y++) {
      if (!used[cands[y].source]) continue
      var ws = cands[y].warnings || []
      for (var w = 0; w < ws.length; w++) {
        if (out.warnings.indexOf(ws[w]) === -1) out.warnings.push(ws[w])
      }
    }

    // A selection or DOM read gives a total but no real line items; if a
    // richer source described the thing, keep its name on the line.
    if (out.items.length === 1 && (!out.items[0].name || out.items[0].name === 'Item' || out.items[0].name === 'Selected amount')) {
      out.items[0].name = out.title || clean(doc.title, 90) || 'Order'
    }

    if (!out.currency) {
      out.currency = ctx.weakCurrency || 'USD'
      out.provenance.currency = ctx.weakCurrencySource || 'default'
      if (!ctx.weakCurrency) out.warnings.push('no currency anywhere on the page — assumed USD')
      else out.warnings.push('currency guessed from ' + ctx.weakCurrencySource + ' (' + out.currency + ')')
    }

    // Rebuild the total from the lines when the lines are the truth.
    if (out.items.length && out.total_minor === null) {
      var sum = 0
      for (var s = 0; s < out.items.length; s++) sum += out.items[s].unit_amount * out.items[s].qty
      if (sum > 0) {
        out.total_minor = sum
        out.provenance.total_minor = out.provenance.items || 'derived'
      }
    }

    out.strategy = PRIORITY.filter(function (p) { return used[p] })
    out.confidence = score(cands, out, used)
    if (!out.title) {
      out.title = clean(doc.title) || out.merchant.name || 'This page'
      out.provenance.title = 'document.title'
    }
    return out
  }

  function score(cands, out, used) {
    var best = 0
    for (var i = 0; i < cands.length; i++) {
      if (!used[cands[i].source]) continue
      if ((cands[i].confidence || 0) > best) best = cands[i].confidence || 0
    }
    // The number is what people act on. Grade on where the *number* came from.
    var owner = out.provenance.total_minor
    var byNumber = {
      'shopify-cart': 0.97, 'json-ld': 0.9, 'shopify-meta': 0.86, 'microdata': 0.78,
      'selection': 0.75, 'og': 0.66, 'dom-total': 0.34, 'buy-action': 0.32, 'derived': 0.6,
    }
    var c = owner && byNumber[owner] !== undefined ? Math.min(best, byNumber[owner]) : best * 0.5
    if (out.total_minor === null) c = Math.min(c, 0.25)
    // Two independent sources agreeing is worth something.
    var agree = 0
    for (var k = 0; k < cands.length; k++) {
      if (cands[k].total_minor === out.total_minor && cands[k].source !== owner) agree++
    }
    if (agree) c = Math.min(0.99, c + 0.04)
    if (out.provenance.currency === 'tld' || out.provenance.currency === 'lang' || out.provenance.currency === 'default') c -= 0.08
    if (out.items.length > 1) c = Math.min(0.99, c + 0.02)
    return Math.max(0.05, Math.min(0.99, Math.round(c * 100) / 100))
  }

  function merchantOf(doc, loc, cands) {
    var host = ''
    var origin = ''
    try {
      host = String(loc.hostname || '')
      origin = String(loc.origin || (loc.protocol + '//' + loc.host) || '')
    } catch (e) {}
    var domain = host.replace(/^www\./, '')
    var name =
      meta(doc, ['og:site_name', 'application-name', 'apple-mobile-web-app-title']) ||
      brandFromDomain(domain) ||
      'Merchant'
    return { name: clean(name, 80) || 'Merchant', url: origin || (domain ? 'https://' + domain : ''), domain: domain }
  }

  var MULTI_TLD = { 'co.uk': 1, 'com.au': 1, 'co.in': 1, 'co.nz': 1, 'co.za': 1, 'com.br': 1, 'co.jp': 1, 'com.sg': 1, 'com.mx': 1, 'co.kr': 1 }

  /** shop.example.com -> "Example". en.wikipedia.org -> "Wikipedia". */
  function brandFromDomain(domain) {
    if (!domain) return null
    var parts = domain.split('.')
    if (parts.length < 2) return null
    var drop = MULTI_TLD[parts.slice(-2).join('.')] ? 2 : 1
    var label = parts[Math.max(0, parts.length - drop - 1)]
    if (!label) return null
    return label.replace(/[-_]+/g, ' ').replace(/^\w/, function (m) { return m.toUpperCase() })
  }

  function safeHref(loc) {
    try {
      return String(loc.href || '')
    } catch (e) {
      return ''
    }
  }

  function weakCurrency(doc, loc) {
    var lang = ''
    try {
      lang = String((doc.documentElement && doc.documentElement.getAttribute('lang')) || '').toLowerCase()
    } catch (e) {}
    if (lang) {
      if (LANG_CURRENCY[lang]) return { code: LANG_CURRENCY[lang], source: 'lang' }
      var base = lang.split('-')[0]
      if (LANG_CURRENCY[base]) return { code: LANG_CURRENCY[base], source: 'lang' }
    }
    var host = ''
    try {
      host = String(loc.hostname || '').toLowerCase()
    } catch (e) {}
    var parts = host.split('.')
    var tld = parts[parts.length - 1]
    if (tld === 'uk' || tld === 'au' || tld === 'nz' || tld === 'za') {
      // co.uk / com.au — the ccTLD is the last label either way.
      if (TLD_CURRENCY[tld]) return { code: TLD_CURRENCY[tld], source: 'tld' }
    }
    if (TLD_CURRENCY[tld]) return { code: TLD_CURRENCY[tld], source: 'tld' }
    return { code: null, source: null }
  }

  // ---------------------------------------------------------------------
  // Entry points
  // ---------------------------------------------------------------------

  function makeCtx(doc, loc, opts) {
    opts = opts || {}
    var win = opts.win
    if (!win) {
      try {
        win = doc.defaultView || (typeof window !== 'undefined' ? window : {})
      } catch (e) {
        win = {}
      }
    }
    var wc = weakCurrency(doc, loc)
    var f = opts.fetch
    if (f === undefined) {
      try {
        f = win && typeof win.fetch === 'function' ? win.fetch.bind(win) : null
      } catch (e) { f = null }
    }
    return {
      win: win || {},
      fetch: f,
      weakCurrency: wc.code,
      weakCurrencySource: wc.source,
      selectionText: opts.selectionText,
      timeoutMs: opts.timeoutMs,
      shopify: opts.shopify,
    }
  }

  function syncCandidates(doc, loc, ctx) {
    var out = []
    out.push(guard(fromSelection, doc, loc, ctx))
    out.push(guard(fromJsonLd, doc, loc, ctx))
    out.push(guard(fromMicrodata, doc, loc, ctx))
    out.push(guard(fromMeta, doc, loc, ctx))
    if (ctx.shopify !== false && isShopify(doc, ctx.win)) out.push(guard(fromShopifyMeta, doc, loc, ctx))
    out = out.filter(Boolean)

    // Scraping the DOM for a total is the last resort in every sense: it is
    // the slowest pass and the only one that can be confidently wrong. Skip it
    // outright when something machine-readable already produced a number.
    var haveGoodNumber = false
    for (var i = 0; i < out.length; i++) {
      if (out[i].total_minor !== null && out[i].total_minor !== undefined && (out[i].confidence || 0) >= 0.66) {
        haveGoodNumber = true
        break
      }
    }
    if (!haveGoodNumber) {
      var dom = guard(fromDomTotal, doc, loc, ctx)
      if (dom) out.push(dom)
      // Last of the last resorts. A product page has no "Total" label to
      // anchor on — it has a price and an "Add to Cart" button — so when
      // nothing above found a number at all, try the price beside that button.
      // This is the only strategy that reaches a marketplace which renders its
      // price in JavaScript, and only from inside a real browser.
      if (!dom || dom.total_minor === null || dom.total_minor === undefined) {
        var buy = guard(fromBuyAction, doc, loc, ctx)
        if (buy) out.push(buy)
      }
    }
    return out
  }

  function guard(fn, doc, loc, ctx) {
    try {
      return fn(doc, loc, ctx)
    } catch (e) {
      return null
    }
  }

  /** Everything except the network. Safe to call anywhere, never rejects. */
  function detectCartSync(doc, loc, opts) {
    doc = doc || (typeof document !== 'undefined' ? document : null)
    loc = loc || (typeof location !== 'undefined' ? location : {})
    if (!doc) return merge([], { title: '', querySelector: function () { return null }, querySelectorAll: function () { return [] } }, loc, makeCtx({ querySelector: function () { return null }, querySelectorAll: function () { return [] } }, loc, opts))
    var ctx = makeCtx(doc, loc, opts)
    return merge(syncCandidates(doc, loc, ctx), doc, loc, ctx)
  }

  /** The full thing, including Shopify's /cart.js. Always resolves. */
  function detectCart(doc, loc, opts) {
    doc = doc || (typeof document !== 'undefined' ? document : null)
    loc = loc || (typeof location !== 'undefined' ? location : {})
    if (!doc) return Promise.resolve(detectCartSync(doc, loc, opts))
    var ctx
    try {
      ctx = makeCtx(doc, loc, opts)
    } catch (e) {
      return Promise.resolve(detectCartSync(doc, loc, opts))
    }
    var sync = syncCandidates(doc, loc, ctx)
    var wantCart = ctx.shopify !== false && isShopify(doc, ctx.win)
    var cartP = wantCart ? guardP(fromShopifyCart, doc, loc, ctx) : Promise.resolve(null)
    return cartP.then(function (cart) {
      return merge(cart ? [cart].concat(sync) : sync, doc, loc, ctx)
    }).catch(function () {
      return merge(sync, doc, loc, ctx)
    })
  }

  function guardP(fn, doc, loc, ctx) {
    try {
      return Promise.resolve(fn(doc, loc, ctx)).catch(function () { return null })
    } catch (e) {
      return Promise.resolve(null)
    }
  }

  return {
    VERSION: VERSION,
    detectCart: detectCart,
    detectCartSync: detectCartSync,
    parseMoney: parseMoney,
    findMoney: findMoney,
    minorUnits: minorUnits,
    formatMinor: formatMinor,
    isShopify: isShopify,
    // exposed for tests
    _internals: {
      jsonLdBlocks: jsonLdBlocks,
      fromJsonLd: fromJsonLd,
      fromMicrodata: fromMicrodata,
      fromMeta: fromMeta,
      fromDomTotal: fromDomTotal,
      fromBuyAction: fromBuyAction,
      fromShopifyCart: fromShopifyCart,
      fromSelection: fromSelection,
      makeCtx: makeCtx,
      parseGrouped: parseGrouped,
    },
  }
})
  /* <<< END INLINED widget/detect.js */

  var SutraDetect = module.exports
  if (!SutraDetect || !SutraDetect.detectCart) return

  // -------------------------------------------------------------------
  // Config
  // -------------------------------------------------------------------

  var NS = '__sutra'
  var STORE_KEY = 'sutra.widget.v1'

  function currentScript() {
    try {
      if (document.currentScript) return document.currentScript
    } catch (e) {}
    var byFlag = document.querySelector('script[data-sutra-widget]')
    if (byFlag) return byFlag
    var all = document.getElementsByTagName('script')
    for (var i = all.length - 1; i >= 0; i--) {
      if ((all[i].src || '').indexOf('widget.js') !== -1) return all[i]
    }
    return null
  }

  var script = currentScript()
  var ds = (script && script.dataset) || {}

  function originOf(u) {
    try {
      return new URL(u).origin
    } catch (e) {
      return null
    }
  }

  var stored = readStore()
  var ENGINE =
    ds.gmpEngine ||
    (script && script.src ? originOf(script.src) : null) ||
    stored.engine ||
    location.origin

  function readStore() {
    try {
      return JSON.parse(localStorage.getItem(STORE_KEY) || '{}') || {}
    } catch (e) {
      return {}
    }
  }
  function writeStore(patch) {
    try {
      var next = readStore()
      for (var k in patch) if (Object.prototype.hasOwnProperty.call(patch, k)) next[k] = patch[k]
      localStorage.setItem(STORE_KEY, JSON.stringify(next))
    } catch (e) {}
  }

  // -------------------------------------------------------------------
  // Formatting
  // -------------------------------------------------------------------

  var SYMBOL = {
    USD: '$', EUR: '€', GBP: '£', INR: '₹', JPY: '¥', KRW: '₩', CAD: 'CA$',
    AUD: 'A$', NZD: 'NZ$', SGD: 'S$', HKD: 'HK$', CHF: 'CHF ', SEK: 'kr ',
    NOK: 'kr ', DKK: 'kr ', PLN: 'zł ', BRL: 'R$', MXN: 'MX$', ZAR: 'R',
    AED: 'AED ', THB: '฿', PHP: '₱', TRY: '₺', ILS: '₪', VND: '₫', IDR: 'Rp ',
  }
  function sym(cur) {
    return SYMBOL[cur] || cur + ' '
  }
  function fmt(minor, cur) {
    if (minor === null || minor === undefined) return '—'
    return sym(cur) + SutraDetect.formatMinor(minor, cur).replace(/\B(?=(\d{3})+(?!\d))/g, ',')
  }
  function toMinor(major, cur) {
    var n = Number(String(major).replace(/[^\d.\-]/g, ''))
    if (!isFinite(n)) return 0
    return Math.round(n * SutraDetect.minorUnits(cur))
  }
  function toMajor(minor, cur) {
    return SutraDetect.formatMinor(minor || 0, cur)
  }

  // -------------------------------------------------------------------
  // DOM helpers (inside the shadow root only)
  // -------------------------------------------------------------------

  function el(tag, attrs, kids) {
    var n = document.createElement(tag)
    if (attrs) {
      for (var k in attrs) {
        if (!Object.prototype.hasOwnProperty.call(attrs, k)) continue
        if (k === 'text') n.textContent = attrs[k]
        else if (k === 'html') n.innerHTML = attrs[k]
        else if (k.slice(0, 2) === 'on') n.addEventListener(k.slice(2), attrs[k])
        else if (attrs[k] !== null && attrs[k] !== undefined) n.setAttribute(k, attrs[k])
      }
    }
    if (kids) {
      for (var i = 0; i < kids.length; i++) {
        if (kids[i]) n.appendChild(typeof kids[i] === 'string' ? document.createTextNode(kids[i]) : kids[i])
      }
    }
    return n
  }

  var CSS = [
    ':host{all:initial}',
    '*{box-sizing:border-box;font-family:ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,sans-serif}',
    '.scrim{position:fixed;inset:0;background:rgba(10,10,12,.62);backdrop-filter:blur(3px);z-index:2147483646;display:flex;align-items:flex-end;justify-content:center;padding:0}',
    '@media(min-width:560px){.scrim{align-items:center;padding:24px}}',
    '.sheet{background:#fbfaf8;color:#14100a;width:100%;max-width:452px;max-height:92vh;overflow:auto;border-radius:18px 18px 0 0;box-shadow:0 24px 70px rgba(0,0,0,.4);animation:up .22s cubic-bezier(.2,.8,.3,1)}',
    '@media(min-width:560px){.sheet{border-radius:18px}}',
    '@keyframes up{from{transform:translateY(18px);opacity:.4}to{transform:none;opacity:1}}',
    '.hd{display:flex;align-items:center;gap:10px;padding:16px 18px 12px;border-bottom:1px solid #ece8e1;position:sticky;top:0;background:#fbfaf8;z-index:2}',
    '.hd b{font-size:15px;font-weight:750;letter-spacing:-.01em;flex:1}',
    '.spark{width:22px;height:22px;border-radius:7px;background:#f59e0b;display:grid;place-items:center;font-size:12px}',
    '.x{border:0;background:#f0ece5;width:28px;height:28px;border-radius:9px;cursor:pointer;font-size:15px;line-height:1;color:#57534e}',
    '.x:hover{background:#e5e0d7}',
    '.bd{padding:16px 18px 20px}',
    '.card{display:flex;gap:12px;align-items:flex-start;background:#fff;border:1px solid #ece8e1;border-radius:13px;padding:12px}',
    '.card img{width:56px;height:56px;object-fit:cover;border-radius:9px;background:#f0ece5;flex:none}',
    '.card .t{flex:1;min-width:0}',
    '.mut{color:#78716c;font-size:12px}',
    '.chips{display:flex;flex-wrap:wrap;gap:5px;margin-top:7px}',
    '.chip{font-size:10.5px;letter-spacing:.04em;text-transform:uppercase;padding:3px 7px;border-radius:6px;background:#f0ece5;color:#57534e;font-weight:650}',
    '.chip.hi{background:#dcfce7;color:#166534}.chip.md{background:#fef3c7;color:#92400e}.chip.lo{background:#fee2e2;color:#991b1b}',
    '.warn{margin-top:10px;font-size:12px;line-height:1.5;color:#92400e;background:#fffbeb;border:1px solid #fde68a;border-left:3px solid #f59e0b;border-radius:8px;padding:9px 11px}',
    '.warn div+div{margin-top:5px}',
    'label{display:block;font-size:11px;font-weight:700;letter-spacing:.06em;text-transform:uppercase;color:#a8a29e;margin:16px 0 6px}',
    'input,select{width:100%;padding:10px 11px;border:1px solid #ddd7cd;border-radius:9px;font-size:14px;background:#fff;color:#14100a}',
    'input:focus,select:focus{outline:2px solid #f59e0b;outline-offset:-1px;border-color:#f59e0b}',
    '.row{display:flex;gap:9px}.row>*{flex:1}.row .qty{max-width:88px}.row .cur{max-width:82px}',
    '.people{display:flex;flex-direction:column;gap:7px}',
    '.person{display:flex;gap:7px;align-items:center}',
    '.person .x{flex:none;width:32px;height:38px;border-radius:9px}',
    '.add{margin-top:7px;border:1px dashed #ddd7cd;background:transparent;color:#78716c;padding:9px;border-radius:9px;width:100%;cursor:pointer;font-size:13px}',
    '.add:hover{border-color:#f59e0b;color:#92400e}',
    '.sum{margin-top:16px;background:#14100a;color:#fbfaf8;border-radius:13px;padding:13px 15px}',
    '.sum .l{display:flex;justify-content:space-between;align-items:baseline;font-size:13px;color:#a8a29e}',
    '.sum .l b{color:#fbfaf8;font-size:19px;font-weight:750}',
    '.sum .l+.l{margin-top:6px}',
    '.cta{margin-top:14px;width:100%;padding:14px;border:0;border-radius:12px;background:#f59e0b;color:#14100a;font-size:15px;font-weight:750;cursor:pointer}',
    '.cta:hover{background:#fbbf24}.cta:disabled{opacity:.55;cursor:progress}',
    '.err{margin-top:12px;font-size:13px;color:#991b1b;background:#fee2e2;border-radius:9px;padding:10px 12px;line-height:1.5}',
    '.mem{display:flex;gap:12px;align-items:center;background:#fff;border:1px solid #ece8e1;border-radius:13px;padding:11px;margin-top:9px}',
    '.mem img{width:84px;height:84px;flex:none;border-radius:9px;background:#f7f5f1}',
    '.mem .t{flex:1;min-width:0}',
    '.mem .n{font-weight:700;font-size:14px}',
    '.mem .a{font-size:19px;font-weight:750;margin:1px 0 7px}',
    '.lnk{display:inline-block;font-size:12px;font-weight:650;color:#92400e;background:#fef3c7;border:0;border-radius:7px;padding:6px 9px;cursor:pointer;text-decoration:none;margin-right:5px}',
    '.lnk:hover{background:#fde68a}',
    '.foot{margin-top:14px;font-size:11.5px;color:#a8a29e;line-height:1.55;border-top:1px solid #ece8e1;padding-top:11px}',
    '.skel{height:11px;border-radius:5px;background:linear-gradient(90deg,#ece8e1,#f7f5f1,#ece8e1);background-size:200% 100%;animation:sh 1.1s linear infinite}',
    '@keyframes sh{to{background-position:-200% 0}}',
    'details{margin-top:14px}summary{font-size:11px;font-weight:700;letter-spacing:.06em;text-transform:uppercase;color:#a8a29e;cursor:pointer}',
    'a{color:#92400e}',
  ].join('')

  // -------------------------------------------------------------------
  // Overrides from data-gmp-* — these always beat what we detected
  // -------------------------------------------------------------------

  function overrides() {
    var o = {}
    if (ds.gmpTitle) o.title = ds.gmpTitle
    if (ds.gmpMerchant) o.merchant = ds.gmpMerchant
    if (ds.gmpCurrency) o.currency = ds.gmpCurrency.toUpperCase()
    if (ds.gmpPrice) o.price = ds.gmpPrice
    if (ds.gmpItem) o.item = ds.gmpItem
    if (ds.gmpQty) o.qty = Number(ds.gmpQty)
    if (ds.gmpMembers) o.members = ds.gmpMembers.split(',').map(function (s) { return s.trim() }).filter(Boolean)
    if (ds.gmpDeadline) o.deadline = Number(ds.gmpDeadline)
    if (ds.gmpPolicy) o.policy = ds.gmpPolicy
    return o
  }

  function applyOverrides(det) {
    var o = overrides()
    var cur = o.currency || det.currency || 'USD'
    var model = {
      title: o.title || det.title || document.title || 'This page',
      merchantName: o.merchant || det.merchant.name,
      merchantUrl: det.merchant.url || location.origin,
      currency: cur,
      itemName: o.item || (det.items[0] && det.items[0].name) || det.title || 'Item',
      unit_amount: o.price !== undefined ? toMinor(o.price, cur) : det.items[0] ? det.items[0].unit_amount : det.total_minor || 0,
      qty: o.qty || (det.items[0] ? det.items[0].qty : 1),
      items: det.items.slice(),
      fees: det.fees.slice(),
      confidence: o.price !== undefined ? 1 : det.confidence,
      strategy: o.price !== undefined ? ['data-gmp-*'] : det.strategy,
      warnings: o.price !== undefined ? [] : det.warnings,
      image: det.image,
      event: det.event,
      kind: det.kind,
      detection: det,
      overridden: !!(o.price !== undefined || o.title || o.item),
    }
    if (o.price !== undefined || !det.items.length) {
      model.items = [{ name: model.itemName, unit_amount: model.unit_amount, qty: model.qty, sku: null }]
    }
    model.members = o.members || stored.members || defaultMembers(model)
    model.policy = o.policy || 'all_of'
    model.deadline = o.deadline || 60
    model.token = ds.gmpToken || stored.token || ''
    return model
  }

  function defaultMembers(model) {
    var n = model.kind === 'event' && model.qty > 1 ? Math.min(model.qty, 8) : 2
    var out = ['You']
    for (var i = 1; i < Math.max(2, n); i++) out.push('Friend ' + i)
    return out
  }

  // -------------------------------------------------------------------
  // The sheet
  // -------------------------------------------------------------------

  var openHost = null

  function closeSheet() {
    if (openHost && openHost.parentNode) openHost.parentNode.removeChild(openHost)
    openHost = null
    document.removeEventListener('keydown', onKey, true)
  }
  function onKey(e) {
    if (e.key === 'Escape') { e.stopPropagation(); closeSheet() }
  }

  function openSheet(opts) {
    opts = opts || {}
    try {
      if (openHost) closeSheet()
      var host = document.createElement('div')
      host.setAttribute('data-sutra-widget-root', '')
      host.style.cssText = 'all:initial;position:fixed;inset:0;z-index:2147483646'
      var root = host.attachShadow ? host.attachShadow({ mode: 'open' }) : host
      root.appendChild(el('style', { text: CSS }))

      var body = el('div', { class: 'bd' })
      var sheet = el('div', { class: 'sheet' }, [
        el('div', { class: 'hd' }, [
          el('div', { class: 'spark', text: '⚡' }),
          el('b', { text: 'Split this with sutra' }),
          el('button', { class: 'x', title: 'Close', text: '✕', onclick: closeSheet }),
        ]),
        body,
      ])
      var scrim = el('div', {
        class: 'scrim',
        onclick: function (e) { if (e.target === scrim) closeSheet() },
      }, [sheet])
      root.appendChild(scrim)
      document.documentElement.appendChild(host)
      openHost = host
      document.addEventListener('keydown', onKey, true)

      renderDetecting(body)
      var selection = ''
      try { selection = String(window.getSelection() || '') } catch (e) {}
      SutraDetect.detectCart(document, location, { selectionText: opts.selectionText !== undefined ? opts.selectionText : selection })
        .then(function (det) {
          renderReview(body, applyOverrides(det))
        })
        .catch(function (err) {
          renderReview(body, applyOverrides(emptyDetection(err)))
        })
    } catch (e) {
      /* the host page must never see this */
    }
  }

  function emptyDetection(err) {
    return {
      title: document.title, merchant: { name: location.hostname, url: location.origin, domain: location.hostname },
      currency: 'USD', items: [], fees: [], total_minor: null, confidence: 0.05,
      strategy: [], warnings: ['detection failed: ' + (err && err.message ? err.message : 'unknown')],
      page_url: location.href, image: null, event: null, kind: null, provenance: {},
    }
  }

  function renderDetecting(body) {
    body.textContent = ''
    body.appendChild(el('div', { class: 'card' }, [
      el('div', { class: 't' }, [
        el('div', { class: 'skel', style: 'width:70%' }),
        el('div', { class: 'skel', style: 'width:45%;margin-top:9px' }),
      ]),
    ]))
    body.appendChild(el('div', { class: 'mut', style: 'margin-top:12px', text: 'Reading this page…' }))
  }

  function confChip(c) {
    var cls = c >= 0.75 ? 'hi' : c >= 0.5 ? 'md' : 'lo'
    var word = c >= 0.85 ? 'high confidence' : c >= 0.75 ? 'good confidence' : c >= 0.35 ? 'low confidence' : 'guess'
    return el('span', { class: 'chip ' + cls, text: word + ' · ' + Math.round(c * 100) + '%' })
  }

  var STRATEGY_LABEL = {
    'shopify-cart': 'your live cart', 'json-ld': 'json-ld', 'shopify-meta': 'shopify',
    microdata: 'microdata', og: 'opengraph', 'dom-total': 'page text',
    selection: 'your selection', 'data-gmp-*': 'merchant tag',
  }

  function renderReview(body, m) {
    body.textContent = ''

    // --- what we found
    var card = el('div', { class: 'card' })
    if (m.image) card.appendChild(el('img', { src: m.image, alt: '', onerror: function () { this.remove() } }))
    var chips = el('div', { class: 'chips' }, [confChip(m.confidence)])
    for (var i = 0; i < m.strategy.length; i++) {
      chips.appendChild(el('span', { class: 'chip', text: STRATEGY_LABEL[m.strategy[i]] || m.strategy[i] }))
    }
    var sub = m.merchantName + (m.event && m.event.start ? ' · ' + niceDate(m.event.start) : '')
    if (m.event && m.event.venue) sub += ' · ' + m.event.venue
    card.appendChild(el('div', { class: 't' }, [
      el('div', { style: 'font-weight:700;font-size:14px;line-height:1.35', text: m.title }),
      el('div', { class: 'mut', style: 'margin-top:2px', text: sub }),
      chips,
    ]))
    body.appendChild(card)

    var notes = m.warnings.slice(0, 4)
    if (m.detection.total_minor === null && !m.overridden) {
      notes.unshift('Nothing on this page looked like a price. Highlight the amount you mean and reopen this, or just type it in below.')
    }
    if (notes.length) {
      var w = el('div', { class: 'warn' })
      for (var j = 0; j < notes.length; j++) w.appendChild(el('div', { text: notes[j] }))
      body.appendChild(w)
    }

    // --- editable
    body.appendChild(el('label', { text: 'What are you splitting' }))
    var titleIn = el('input', { value: m.title, maxlength: '140' })
    body.appendChild(titleIn)

    body.appendChild(el('label', { text: 'Price each · quantity' }))
    var curIn = el('input', { class: 'cur', value: m.currency, maxlength: '3' })
    var priceIn = el('input', { value: toMajor(m.unit_amount, m.currency), inputmode: 'decimal' })
    var qtyIn = el('input', { class: 'qty', value: String(m.qty), type: 'number', min: '1', max: '99' })
    body.appendChild(el('div', { class: 'row' }, [curIn, priceIn, qtyIn]))

    if (m.items.length > 1) {
      body.appendChild(el('div', { class: 'mut', style: 'margin-top:7px' }, [
        document.createTextNode('Detected ' + m.items.length + ' lines totalling ' + fmt(sumItems(m.items), m.currency) + '. '),
        el('span', { text: 'Editing above collapses them into one line.' }),
      ]))
    }

    body.appendChild(el('label', { text: 'Who is paying' }))
    var people = el('div', { class: 'people' })
    body.appendChild(people)
    var addBtn = el('button', { class: 'add', text: '+ add someone' })
    body.appendChild(addBtn)

    function person(name) {
      var input = el('input', { value: name, placeholder: 'Name', maxlength: '60' })
      var rm = el('button', {
        class: 'x', text: '−', title: 'Remove',
        onclick: function () { if (people.children.length > 1) { row.remove(); update() } },
      })
      var row = el('div', { class: 'person' }, [input, rm])
      input.addEventListener('input', update)
      return row
    }
    for (var p = 0; p < m.members.length; p++) people.appendChild(person(m.members[p]))
    addBtn.addEventListener('click', function () {
      if (people.children.length >= 20) return
      people.appendChild(person('Friend ' + people.children.length))
      update()
    })

    var det = el('details', {}, [el('summary', { text: 'Policy, deadline, connection' })])
    var policyIn = el('select', {}, [
      el('option', { value: 'all_of', text: 'Everyone must approve' }),
      el('option', { value: 'quorum', text: 'Quorum — most of us is enough' }),
      el('option', { value: 'deadline', text: 'Deadline — whoever is in by then' }),
    ])
    policyIn.value = m.policy
    var deadlineIn = el('input', { value: String(m.deadline), type: 'number', min: '1', max: '10080' })
    var tokenIn = el('input', { value: m.token, placeholder: 'engine API token', type: 'password' })
    var engineIn = el('input', { value: ENGINE, placeholder: 'https://engine.example.com' })
    det.appendChild(el('label', { text: 'Approval policy' }))
    det.appendChild(policyIn)
    det.appendChild(el('label', { text: 'Deadline (minutes)' }))
    det.appendChild(deadlineIn)
    det.appendChild(el('label', { text: 'Engine' }))
    det.appendChild(engineIn)
    det.appendChild(el('label', { text: 'API token' }))
    det.appendChild(tokenIn)
    body.appendChild(det)
    if (!m.token) det.setAttribute('open', '')

    var totalLine = el('b', { text: '—' })
    var eachLine = el('span', { text: '' })
    body.appendChild(el('div', { class: 'sum' }, [
      el('div', { class: 'l' }, [el('span', { text: 'Total' }), totalLine]),
      el('div', { class: 'l' }, [el('span', { text: 'Each' }), eachLine]),
    ]))

    var cta = el('button', { class: 'cta', text: 'Request payment' })
    body.appendChild(cta)
    var errBox = el('div')
    body.appendChild(errBox)
    body.appendChild(el('div', { class: 'foot' }, [
      document.createTextNode('Each person approves their own share. The cap is enforced by the card network, not by this page. '),
      el('span', { text: 'Read from ' + (m.detection.provenance.total_minor || 'nothing') + '.' }),
    ]))

    function names() {
      var out = []
      for (var i = 0; i < people.children.length; i++) {
        var v = people.children[i].firstChild.value.trim()
        if (v) out.push(v)
      }
      return out
    }
    function currency() {
      return (curIn.value || 'USD').toUpperCase().slice(0, 3)
    }
    function total() {
      return toMinor(priceIn.value, currency()) * Math.max(1, Number(qtyIn.value) || 1)
    }
    function update() {
      var cur = currency()
      var t = total()
      var n = Math.max(1, names().length)
      totalLine.textContent = fmt(t, cur)
      eachLine.textContent = fmt(Math.floor(t / n), cur) + ' × ' + n
      cta.textContent = 'Request payment from ' + n + (n === 1 ? ' person' : ' people')
    }
    ;[titleIn, curIn, priceIn, qtyIn].forEach(function (n) { n.addEventListener('input', update) })
    update()

    cta.addEventListener('click', function () {
      errBox.textContent = ''
      var cur = currency()
      var unit = toMinor(priceIn.value, cur)
      var qty = Math.max(1, Number(qtyIn.value) || 1)
      var who = names()
      var engine = (engineIn.value || ENGINE).replace(/\/+$/, '')
      if (unit <= 0) return fail(errBox, 'Set a price above zero — nothing gets sent until you do.')
      if (!who.length) return fail(errBox, 'Add at least one person.')
      if (!/^[A-Z]{3}$/.test(cur)) return fail(errBox, 'Currency must be a 3-letter code like USD or INR.')

      writeStore({ members: who, token: tokenIn.value, engine: engine })
      cta.disabled = true
      cta.textContent = 'Creating mandates…'

      createGroup(engine, tokenIn.value, {
        title: titleIn.value.slice(0, 140) || 'Group purchase',
        merchantName: m.merchantName,
        merchantUrl: m.merchantUrl,
        currency: cur,
        itemName: (titleIn.value || m.itemName).slice(0, 100),
        unit_amount: unit,
        qty: qty,
        fees: m.fees,
        members: who,
        policy: policyIn.value,
        deadline: Math.max(1, Number(deadlineIn.value) || 60),
      })
        .then(function (group) { renderDone(body, group, engine, cur) })
        .catch(function (err) {
          cta.disabled = false
          update()
          fail(errBox, String(err && err.message ? err.message : err))
        })
    })
  }

  function fail(box, msg) {
    box.textContent = ''
    box.appendChild(el('div', { class: 'err', text: msg }))
  }

  function sumItems(items) {
    var s = 0
    for (var i = 0; i < items.length; i++) s += items[i].unit_amount * items[i].qty
    return s
  }

  function niceDate(iso) {
    try {
      var d = new Date(iso)
      if (isNaN(d.getTime())) return iso
      return d.toLocaleString(undefined, { weekday: 'short', month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' })
    } catch (e) {
      return iso
    }
  }

  // -------------------------------------------------------------------
  // Engine — POST /v1/groups (see engine/src/routes.ts)
  // -------------------------------------------------------------------

  function createGroup(engine, token, o) {
    var quorum = Math.max(1, Math.ceil(o.members.length * 0.6))
    var policy =
      o.policy === 'quorum' ? { type: 'quorum', m: quorum }
        : o.policy === 'deadline'
          ? {
              type: 'deadline',
              at: new Date(Date.now() + o.deadline * 60000).toISOString(),
              primary: { type: 'all_of' },
              fallback: { type: 'quorum', m: quorum },
            }
          : { type: 'all_of' }

    var body = {
      title: o.title,
      merchant: {
        id: 'widget',
        name: o.merchantName.slice(0, 80),
        url: /^https?:\/\//.test(o.merchantUrl) ? o.merchantUrl : 'https://' + location.hostname,
        country_code_iso2: (navigator.language || 'en-US').split('-')[1] || 'US',
      },
      cart: {
        items: [{
          sku: 'sutra-widget-1',
          name: o.itemName || 'Item',
          unit_amount: o.unit_amount,
          qty: o.qty,
          claimants: ['mi_all'],
        }],
        fees: (o.fees || []).slice(0, 8).map(function (f, i) {
          return { name: String(f.name || 'Fee ' + (i + 1)).slice(0, 60), amount: Math.max(0, Math.round(f.amount || 0)) }
        }),
        currency: o.currency,
      },
      members: o.members.slice(0, 20).map(function (n) { return { name: n.slice(0, 60), role: 'payer' } }),
      policy: policy,
      deadline_minutes: Math.min(10080, o.deadline),
    }

    return fetch(engine + '/v1/groups', {
      method: 'POST',
      headers: { 'content-type': 'application/json', authorization: 'Bearer ' + (token || 'dev-token') },
      body: JSON.stringify(body),
    }).then(function (res) {
      return res.text().then(function (raw) {
        if (!res.ok) {
          var msg = raw
          try { msg = JSON.parse(raw).error || raw } catch (e) {}
          if (res.status === 401) msg = 'The engine rejected the token. Open “Policy, deadline, connection” and paste a valid API token.'
          throw new Error('Engine said ' + res.status + ': ' + String(msg).slice(0, 200))
        }
        return JSON.parse(raw)
      })
    })
  }

  function renderDone(body, group, engine, currency) {
    body.textContent = ''
    body.appendChild(el('div', { class: 'card' }, [
      el('div', { class: 't' }, [
        el('div', { style: 'font-weight:750;font-size:15px', text: '✓ ' + group.members.length + ' mandates requested' }),
        el('div', { class: 'mut', style: 'margin-top:3px', text: 'Each person scans their own code and approves their own share. Nothing is charged until the policy is satisfied.' }),
      ]),
    ]))

    for (var i = 0; i < group.members.length; i++) {
      (function (mem) {
        var qr = engine + '/v1/members/' + mem.member_id + '/qr.png'
        var copy = el('button', { class: 'lnk', text: 'copy link' })
        copy.addEventListener('click', function () {
          try {
            navigator.clipboard.writeText(mem.approval_page_url)
            copy.textContent = 'copied ✓'
            setTimeout(function () { copy.textContent = 'copy link' }, 1400)
          } catch (e) {
            copy.textContent = mem.approval_page_url
          }
        })
        body.appendChild(el('div', { class: 'mem' }, [
          el('img', { src: qr, alt: 'QR for ' + mem.name, loading: 'lazy' }),
          el('div', { class: 't' }, [
            el('div', { class: 'n', text: mem.name }),
            el('div', { class: 'a', text: fmt(mem.share_amount, currency) }),
            el('a', { class: 'lnk', href: mem.approval_page_url, target: '_blank', rel: 'noopener', text: 'open →' }),
            copy,
          ]),
        ]))
      })(group.members[i])
    }

    body.appendChild(el('a', {
      class: 'cta', style: 'display:block;text-align:center;text-decoration:none;margin-top:16px',
      href: group.board_url, target: '_blank', rel: 'noopener', text: 'Watch the board live →',
    }))
    body.appendChild(el('div', { class: 'foot', text: 'Group ' + group.group_id + ' · caps are enforced at the card network. Close this page; the board keeps running.' }))
  }

  // -------------------------------------------------------------------
  // Mount
  // -------------------------------------------------------------------

  function mountButton() {
    if (!script || !script.parentNode) return null
    var btn = el('button', { text: '⚡ Split this with sutra' })
    btn.style.cssText =
      'all:initial;font-family:ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,sans-serif;' +
      'padding:14px 22px;border-radius:12px;border:0;background:#f59e0b;color:#14100a;' +
      'font-size:16px;font-weight:700;cursor:pointer;display:inline-block;line-height:1'
    btn.addEventListener('click', function () { openSheet() })
    try {
      script.parentNode.insertBefore(btn, script)
    } catch (e) {
      return null
    }
    return btn
  }

  function mountFloating() {
    var host = document.createElement('div')
    host.setAttribute('data-sutra-widget-launcher', '')
    host.style.cssText = 'all:initial;position:fixed;right:18px;bottom:18px;z-index:2147483645'
    var root = host.attachShadow ? host.attachShadow({ mode: 'open' }) : host
    root.appendChild(el('style', {
      text:
        ':host{all:initial}button{font-family:ui-sans-serif,system-ui,-apple-system,sans-serif;' +
        'padding:13px 18px;border-radius:999px;border:0;background:#f59e0b;color:#14100a;font-size:14px;' +
        'font-weight:750;cursor:pointer;box-shadow:0 8px 26px rgba(0,0,0,.28)}button:hover{background:#fbbf24}',
    }))
    root.appendChild(el('button', { text: '⚡ Split this', onclick: function () { openSheet() } }))
    document.documentElement.appendChild(host)
    return host
  }

  // One global. It exists so a second injection is a no-op and so the
  // bookmarklet and the extension have something to call.
  var api = window[NS]
  if (api && api.open) {
    // Already on the page — just reopen with the current selection.
    try { api.open() } catch (e) {}
    return
  }
  api = {
    version: '2.0.0',
    engine: ENGINE,
    open: function (opts) { openSheet(opts) },
    close: closeSheet,
    detect: function (opts) { return SutraDetect.detectCart(document, location, opts || {}) },
    Detect: SutraDetect,
  }
  try {
    Object.defineProperty(window, NS, { value: api, writable: false, configurable: true, enumerable: false })
  } catch (e) {
    window[NS] = api
  }

  try {
    // mount=none is what the bookmarklet and the extension pass: they are the
    // launcher, so a second button on the page would just be litter.
    if (ds.gmpMount === 'none') { /* the caller opens the sheet itself */ }
    else if (ds.gmpMount === 'float') mountFloating()
    else if (!mountButton()) mountFloating()
    if (ds.gmpAuto === '1' || ds.gmpAuto === 'true' || (script && script.hasAttribute('data-sutra-open'))) openSheet()
  } catch (e) {}
})()
